name: Update Telemetry Index

on:
  push:
    paths:
      - 'public/data/telemetry/*.json'
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Update Telemetry Index
        run: |
          npm run update-telemetry
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/telemetry/index.json
          git commit -m "Update telemetry index" || echo "No changes to commit"
          git push 